<?php

include("conexion.php");
$con=conectar();

$CÓDIGO_COMPONENTE=$_POST['CÓDIGO_COMPONENTE'];
$TIPO_DE_COMPONENTE=$_POST['TIPO_DE_COMPONENTE'];
$NOMBRE=$_POST['NOMBRE'];
$MODELO=$_POST['MODELO'];
$PRECIO=$_POST['PRECIO'];
$ENSAMBLADORA=$_POST['ENSAMBLADORA'];
$CONTRATISTA=$_POST['CONTRATISTA'];
$PAÍS_DE_ENVÍO=$_POST['PAÍS_DE_ENVÍO'];
$FECHA_DE_PEDIDO=$_POST['FECHA_DE_PEDIDO'];
$FECHA_LLEGADA=$_POST['FECHA_LLEGADA'];
$CANTIDAD=$_POST['CANTIDAD'];


$sql="UPDATE base_pc_global SET  TIPO_DE_COMPONENTE='$TIPO_DE_COMPONENTE',NOMBRE='$NOMBRE',MODELO='$MODELO',PRECIO='$PRECIO',ENSAMBLADORA='$ENSAMBLADORA',CONTRATISTA='$CONTRATISTA',PAÍS_DE_ENVÍO='$PAÍS_DE_ENVÍO',FECHA_DE_PEDIDO='$FECHA_DE_PEDIDO',FECHA_LLEGADA='$FECHA_LLEGADA',CANTIDAD='$CANTIDAD' WHERE CÓDIGO_COMPONENTE='$CÓDIGO_COMPONENTE'";
$query=mysqli_query($con,$sql);

    if($query){
        Header("Location: inventario.php");
    }
?>